/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jeffrpowell.flashcards.view;

import jeffrpowell.flashcards.controller.Controller;

/**
 *
 * @author Jeff
 */
public class ButtonBar extends javax.swing.JPanel {
    private final Controller controller;
    /**
     * Creates new form ButtonBar
     */
    public ButtonBar(Controller controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDeckButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        editDeckBtn = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        runDeckBtn = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        addDeckButton.setText("Add a New Deck");
        addDeckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDeckButtonActionPerformed(evt);
            }
        });
        add(addDeckButton);
        add(filler1);

        editDeckBtn.setText("Edit Existing Deck");
        editDeckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDeckBtnActionPerformed(evt);
            }
        });
        add(editDeckBtn);
        add(filler2);

        runDeckBtn.setText("Run Through Deck");
        runDeckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runDeckBtnActionPerformed(evt);
            }
        });
        add(runDeckBtn);
    }// </editor-fold>//GEN-END:initComponents

    private void addDeckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDeckButtonActionPerformed
        controller.addButtonClicked();
    }//GEN-LAST:event_addDeckButtonActionPerformed

    private void editDeckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDeckBtnActionPerformed
        controller.editButtonClicked();
    }//GEN-LAST:event_editDeckBtnActionPerformed

    private void runDeckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runDeckBtnActionPerformed
        controller.runButtonClicked();
    }//GEN-LAST:event_runDeckBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDeckButton;
    private javax.swing.JButton editDeckBtn;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton runDeckBtn;
    // End of variables declaration//GEN-END:variables
}
